### ISSUE TITLE
Enable more than one version of php

### ISSUE THREAD

**Issue by frankcarey** [zivtech/vagrant-development-vm#10]
Drupal 8 requires 5.4, and it would be nice to support multiple versions in parallel instead of replacing it. I'm testing out phpenv right now, which allows multiple php versions like rbenv (See http://mile23.com/content/using-phpenv-and-php-build-your-ubuntu). I'll report back how it goes.

**Comment by frankcarey** [comment]
Right off the bat, you hit errors about missing packages to build php (note that I installed php-build as a plugin of rbenv per the README in php-build.) The article in the above comment has a copy&paste list of dependencies that I installed. (I needed to refresh my sources with `sudo apt-get update`)

For reference, that list is below, and it installed fairly quickly:
`make re2c bison libxml2-dev libssl-dev libbz2-dev libcurl3-dev libdb5.1-dev libjpeg-dev libpng-dev libXpm-dev libfreetype6-dev libt1-dev libgmp3-dev libc-client-dev libldap2-dev libmcrypt-dev libmhash-dev freetds-dev libz-dev libmysqlclient15-dev ncurses-dev libpcre3-dev unixODBC-dev postgresql-server-dev-9.1 libsqlite-dev libaspell-dev libreadline6-dev librecode-dev libsnmp-dev libtidy-dev libxslt-dev libt1-dev`

then I ran phpenv install 5.4.36, which downloaded the source and compiled it. Took like 5-8 minutes to compile it.

Php CLI worked well, but apache didn't work out of the box. I added the following line to the default config in ~/.phpenv/plugins/php-build/share/php-build/default_configure_options

`--with-apxs2=/usr/bin/apxs2`

Then recompiled.. and failed because it was trying to copy the file into /usr/lib/apache2/modules/libphp5.so but didn't have permissions..

...then recompiled again with sudo and it installed. Restarting apache shows the 5.4 version now, but it doesn't allow for switching since it blew the old one away. This works for me now so I'm punting off finishing it up. Sounds like the linking issue is ignoring prefix? .. See http://askubuntu.com/questions/263092/compiling-php-5-2-from-source-under-12-04-apxs2-via-libtools-ignores-the-pre

There is another plugin that is supposed to do the apache swtiching, but it can't find the libphp5.so file in the compiled /versions folders. See https://github.com/garamon/phpenv-apache-version

There is a puppet for phpenv that I found as well. See https://github.com/phpops/puppet-phpenv/blob/master/manifests/init.pp

**Comment by tizzo** [comment]
Yeah, I've been thinking about the php versioning issue for a while.  PHP env is definitely one approach, though I think what might be cleaner would be to encapsulate apache in a docker container where we could run php versions in parallel.  I imagine doing this by using [hipache]() to proxy all connections to the appropriate site and mounting the `/var/www` and `/etc/apache2` folders into the docker containers.  This way you could switch php versions just by changing a redis value (through some wrapper script) and by default all sites would be served by whatever the default version was.

The thorny issue with it would be drush.  I think what we might need to do is have `drush` actually be a bash (or php?) script that would run the drush command inside the appropriate container based on some configuration file in the parent directory.  This way it could be completely transparent to the user what version a site was hosted on and a single command could switch the version for php and CLI use.   It could be confusing for php scripts that were manually executed… unless we wrapped `php` in a script that looked up the appropriate container as well…

**Comment by frankcarey** [comment]
How about fastcgi? You can declare in each site files which fastcgi
versions/files to point to I think.

Another option might be php's internal webserver. I've been using it for
running tests with Codeship and while it took a minute to figure out how to
get clean urls working, it seems to work pretty well actually.


Cheers,

Frank Carey

**Comment by sk33lz** [comment]
@frankcarey we now have the ability to run different Ubuntu versions if you copy the `default.config.yaml` and name the new file `config.yaml`. You can then specify which box file and version to use in the following lines:

    # The base box to use to build the puppet work on top of.
    # Commenting out the two lines below (or overriding in config,yaml)
    # to switch to 12.04.
    box: "puppetlabs/ubuntu-14.04-64-puppet-1.0.0"
    box_url: "https://atlas.hashicorp.com/puppetlabs/boxes/ubuntu-14.04-64-puppet/versions/1.0.0/providers/virtualbox.box"
    # Un-comment the next two lines, to use 12.04
    #box: "puppetlabs/ubuntu-12.04-64-puppet-1.0.0"
    #box_url: "https://atlas.hashicorp.com/puppetlabs/boxes/ubuntu-12.04-64-puppet/versions/1.0.0/providers/virtualbox.box"

While it's not "in parallel" in the sense that you are describing in your OP, you can spin up a 12.04 and a 14.04 VM to get the versions of PHP needed to run Drupal 6-8 sites side by side (if you have the RAM). Otherwise, you can just `vagrant up` and `vagrant halt` as needed for each VM.

Please mark this as resolved if you feel this is a sufficient fix for the original issue. Thanks! If not, PRs are always welcome :)

**Comment by sk33lz** [comment]
This can definitely be set in our latest VM release with the following hiera value:

`php::globals::php_version`

See https://github.com/zivtech/vagrant-development-vm/blob/master/hiera/common.yaml#L14.
