### ISSUE TITLE
Apt-get update failing during provision

### ISSUE THREAD

**Issue by jodyHamilton** [zivtech/vagrant-development-vm#11]
apt-get update was failing for me during provision
Adding
    config.vm.provision :shell, :inline => "apt-get update --fix-missing"
to VagrantFile resolved it

**Comment by tizzo** [comment]
PR welcome ;)

**Comment by jodyHamilton** [comment]
I don't understand the problem or fix well enough to propose a patch, just leaving this here in case others run into the issue. Perhaps it only occurs on 2008 imacs...

**Comment by tizzo** [comment]
Could you post the logs that you saw?  I don't know what you mean by
"apt-get update was failing" - that's pretty broad and could mean a number
of things.

This puppet setup runs `apt-get update` and `apt-get upgrade` as a first
step before doing anything else.  In theory, that should work if running it
as a shell provisioner works too.  Adding the shell provision run is fine
and might be cleaner than having it happen in puppet anyway.

**Comment by jodyHamilton** [comment]
Not really because my terminal doesn't scroll back far enough. It was similar to this error (from a bug report i googled) but different paths:

    err: /Stage[main]/Apt/Exec[/usr/bin/apt-get update]: Failed to call refresh: /usr/bin/apt-get update returned 100 instead of one of [0] at /tmp/vagrant-puppet/modules-0/apt/manifests/init.pp:80

**Comment by tizzo** [comment]
My bet is it was a one-off network error.

If not reopen.  Also - you should set iterms scrollback to be bigger or
unlimited - you'll thank me.

**Comment by Frug** [comment]
Thanks @jodyHamilton for the fix. I had the same problem and this works well.
It may just be a one-off issue, but it seems puppet doesn't know how to handle that.

**Comment by sk33lz** [comment]
We have a bit of a different line in our puppet master config, so I am going to use that line instead and test locally. PR upcoming if that works out.
