### ISSUE TITLE
Drush cannot find database connection after "drush fec"

### ISSUE THREAD

**Issue by allisondev** [zivtech/vagrant-development-vm#19]
After using "drush fec" in attempt to create a new local site at /var/www, I get the following error. 

Exception 'Drush\Sql\SqlException' with message 'Unable to find a  [error]
matching SQL Class. Drush cannot find your database connection
details.' in /var/lib/drush/commands/sql/sql.drush.inc:597

On master, commit: 9cdf8eb156aa1961d10fe140c0af3fe711718cfc

**Comment by allisondev** [comment]
- I was using ubuntu-14.04.
- Command used: `drush fec test`

Here's the end of the log displayed on screen after running the command.

``exception 'Drush\Sql\SqlException' with message 'Unable to find a matching SQL Class. Drush cannot find your database connection details.' in      [error]
/var/lib/drush/commands/sql/sql.drush.inc:597
Stack trace:
#0 /var/lib/drush/commands/core/site_install.drush.inc(107): drush_sql_get_class()
#1 [internal function]: drush_core_pre_site_install('standard')
#2 /var/lib/drush/includes/command.inc(364): call_user_func_array('drush_core_pre_...', Array)
#3 /var/lib/drush/includes/command.inc(215): _drush_invoke_hooks(Array, Array)
#4 [internal function]: drush_command('standard')
#5 /var/lib/drush/includes/command.inc(183): call_user_func_array('drush_command', Array)
#6 /var/lib/drush/lib/Drush/Boot/BaseBoot.php(62): drush_dispatch(Array)
#7 /var/lib/drush/drush.php(70): Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#8 /var/lib/drush/drush.php(11): drush_main()
#9 {main}
Admin user created with username `admin` and password `pass`.
``

The 'test' database was created, but the site wasn't connected to it. When I went to test.local, i get the install page.

**Comment by tizzo** [comment]
Looks like this was related to a fix we created recently to fix fetcher's multiple version support.  I patched fetcher and I believe this is now working. I also updated Zivtech's internal config to use drush 8.0.2 by default (the VM will still install drush on master).

**Comment by tizzo** [comment]
@allisondev Can you test and verify this is resolved?

**Comment by allisondev** [comment]
@tizzo I tested that's correct. This issue is fixed with the latest fetcher commit. I created a PR to update the fetcher commit in hiera/common.yaml:

https://github.com/zivtech/vagrant-development-vm/pull/20

**Comment by tizzo** [comment]
This got merged. Sorry it took so long.
