### ISSUE TITLE
Fix Drush on Ubuntu 12.04

### ISSUE THREAD

**Issue by lliss** [zivtech/vagrant-development-vm#26]
By default the VM downloads the latest version of Drush. This version is not supported by PHP 5.3 which is the default on Ubuntu 12.04.

**Comment by tizzo** [comment]
Yeah, we probably should have a hiera file for the lsb codename as we do on Zivtech's private `puppet-master` repo.

**Comment by sk33lz** [comment]
Do we even care about 12.04 anymore since it's deprecated?

**Comment by lliss** [comment]
Nope.
