### ISSUE TITLE
Install error = stdin: is not a tty

### ISSUE THREAD

**Issue by Topplestack** [zivtech/vagrant-development-vm#9]
Running OSX 10.9.3

The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

puppet apply --modulepath '/tmp/vagrant-puppet-3/modules-0:/etc/puppet/modules' --manifestdir /tmp/vagrant-puppet-3/manifests --detailed-exitcodes /tmp/vagrant-puppet-3/manifests/base.pp

Stdout from the command:

Stderr from the command:

stdin: is not a tty
Puppet::Parser::AST::Resource failed with error ArgumentError: Could not find declared class webadmin at /tmp/vagrant-puppet-3/manifests/base.pp:32 on node local.*******.com

**Comment by sk33lz** [comment]
This is fixed in 665685c87df6bafdfb45c23df478352271764721.
